In [ ]:
import keras
import numpy as np

In [ ]:
#@title Capa de keras que transforma las predicciones en labels categoticos
#@markdown Genera labels de 1s o 0s acorde a la discriminación del vector.
#@markdown La mencionada el miercoles en la reunión

class LayerExpand(keras.layers.Layer):
    def __init__(self, stacks):
        super(LayerExpand,self).__init__()
        self.stacks = stacks

    def call(self, arr):
        list_arr = []
        categorical = self.analyser(arr)
        for stack in range(self.stacks):
            if categorical[stack] == 1:
                list_arr.append(np.full((1,self.stacks),1))
            else:
                list_arr.append(np.full((1,self.stacks),0))

        return list_arr

    def analyser(self, arr):
        err = 0.0001
        label = np.zeros((arr.shape[0]))

        for i in range(arr.shape[0]):
            if arr[i] >= err: label[i] = 1

        return label


In [ ]:
var = LayerExpand(5)

In [ ]:
var(np.array([7.2552335e-05, 6.6169314e-02, 1.5318026e-06, 1.5946893e-01,
        9.8755634e-01]))

[array([[0, 0, 0, 0, 0]]),
 array([[1, 1, 1, 1, 1]]),
 array([[0, 0, 0, 0, 0]]),
 array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]])]

In [ ]:
#@title Capa de keras que transforma las predicciones en labels categoticos
#@markdown Solamente genera labels con aquellos elementos del arreglo original que son valor 1.
#@markdown La programada.
class LayerExpandState(keras.layers.Layer):
    def __init__(self, stacks):
        super(LayerExpandState,self).__init__(trainable=False)
        self.stacks = stacks

    def call(self, labels):
        return self.getLabels(labels)

    def getLabels(self, arr):
        list_ = []
        vector = self.analyser(arr)
        idx_labels = np.where(vector == 1)[0]
        for i in idx_labels:
            list_.append(self.to_labels(i, arr.shape[0]))

        return np.array(list_)

    def analyser(self, arr):
        err = 0.0001
        label = np.zeros((arr.shape[0]))

        for i in range(arr.shape[0]):
            if arr[i] >= err: label[i] = 1

        return label

    def to_labels(self, idx, S):
        arr = np.zeros(S)
        arr[idx] = 1
        return arr





In [ ]:
aa=LayerExpandState(5)


In [ ]:
#@markdown salida esperada: [0,1,0,0,0]-[0,0,0,1,0]-[0,0,0,0,1]
aa(np.array([7.2552335e-05, 6.6169314e-02, 1.5318026e-06, 1.5946893e-01,
        9.8755634e-01]))

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])