In [1]:
%cd CPMP-ML

h:\Mi unidad\PUCV\CPMP_With_attetion\CPMP-ML


In [2]:
import numpy as np
from keras.utils import to_categorical
import cpmp_ml
from cpmp_ml import generate_random_layout
from cpmp_ml import generate_data, get_move, generate_data2
from copy import deepcopy
import CPMP_attention_model as cpmp_att

In [3]:
%cd ..

h:\Mi unidad\PUCV\CPMP_With_attetion


## Algoritmo Greedy y funciones para generación de datos

In [4]:
#************* | Función is_valid_BG_move() | ****************#
# El proposito de esta función es validar si el movimiento    #
# dentro del estado actual del problema actual al que se le   #
# desea realizar sirve para resolver el problema o no.        #  
#                                                             #
# Input:                                                      #
#     - layout: Variable que contiene el estado al que se     #
#               le desea realizar el movimiento.              #
#     - s_o: Stack de origen                                  #
#     - S_d: Stack de destino                                 #
#                                                             #
# Output:                                                     #
#     La función retorna True en caso de ser un movimiento    #
#     posible o False en caso contrario.                      #
def is_valid_BG_move(layout: cpmp_ml.Layout, s_o: int, s_d: int) -> bool:
    if (s_o != s_d  and len(layout.stacks[s_o]) > 0
    and  len(layout.stacks[s_d]) < layout.H
    and layout.is_sorted_stack(s_o)==False
    and layout.is_sorted_stack(s_d)==True
    and layout.gvalue(s_o) <= layout.gvalue(s_d)):
      return True

    else: return False

In [5]:
#*********** | Función select_bg_move() | ************#
# El proposito de esta función es seleccionar un      #
# movimiento que optimice la diferencia entre las     #
# prioridades entre los contenedores del stack de     #
# destino y el stack de origen.                       #
#                                                     #
# Input:                                              #
#     - layout: Variable que contiene el estado       #
#               actual al que se le desea realizar    #
#               el movimiento.                        #
#                                                     #
# Output:                                             #
#   Retorna una tupla indicando el stack de origen    #
#   y el stack de destino que minimiza la             #
#   diferencia antes mencionada o en caso contrario   #
#   retorna None.                                     #
def select_bg_move(layout: cpmp_ml.Layout) -> tuple:
  bg_move = None # Tupla de movimiento optimo
  S=len(layout.stacks) # Cantidad de stacks
  min_diff = 100
  for s_o in range(S):
     for s_d in range(S):
       if is_valid_BG_move(layout, s_o, s_d):
          diff = layout.gvalue(s_d) - layout.gvalue(s_o)
          if min_diff > diff:
            min_diff = diff
            bg_move = (s_o,s_d)
  return bg_move

In [6]:
#************* | Función greedy | **************#
# El proposito de esta función es utilizar un   #
# algoritmo greedy para resolver el problema    #
# CPMP.                                         #
#                                               #
# Input:                                        #
#     - layout: El estado al cual se le desea   #
#               aplicar el algoritmo greedy     #
#               para resolverlo.                #
# Output:                                       #
#     La función retorna la cantidad de         #
#     movimientos que toma resolver el problema #
#     con el algoritmo y los movimientos que    #
#     debe llevar a cabo, en caso de no poder   #
#     ser resuelto retorna como cantidad de     #
#     pasos -1 y None en movimientos.           #
def greedy(layout: cpmp_ml.Layout) -> tuple:
    moves = []
    steps = 0
    while layout.unsorted_stacks>0:
        bg_move=select_bg_move(layout)
        if bg_move is not None:
            moves.append(bg_move)
            layout.move(bg_move)
        else:
            return -1, None # no lo resuelve
        steps +=1

    if layout.unsorted_stacks==0:
        return steps, moves
    return -1, None

In [7]:
#**************** | Función unlist() | ***************#
# El proposito de esta función es unificar las        #
# diversas listas de datos con los nuevos datos a     #
# ingresar.                                           #
#                                                     #
# Input:                                              #
#     - data: Lista de matrices principal.            #
#     - labels1: Lista de stacks de origen principal. #
#     - labels2: Lista de stacks de destino principal.#
#     - state: Lista de matrices con nuevos datos.    #
#     - source: Lista de stacks de origen con nuevos  #
#               datos.                                #
#     - destination: Lista de stacks de destino con   #
#                    nuevos datos.                    #
#                                                     #
# Output:                                             #
#     No retorna valores.                             #
def unlist(data: list, labels1: list, labels2: list, 
           state: list, source: list, destination: list
           ) -> None:
  n = len(source) # Cantidad de datos nuevos
  for i in range(n):
    data.append(state[i])
    labels1.append(source[i])
    labels2.append(destination[i])

In [8]:
#************* | get_ann_state() | **************#
# El proposito de esta función preparar los      #
# datos de un estado del problema CPMP para que  #
# pueda ser leído por una red neuronal.          #
#                                                #
# Input:                                         #
#     - layout: Estado actual del problema CPMP. #
#                                                #
# Output:                                        #
#     Retorna una matriz con los datos           #
#     normalizados.                              #
def get_ann_state(layout: cpmp_ml.Layout) -> np.ndarray:
  S=len(layout.stacks) # Cantidad de stacks
  #matriz de stacks
  b = 2. * np.ones([S,layout.H + 1]) # Matriz normalizada
  for i,j in enumerate(layout.stacks):
     b[i][layout.H-len(j) + 1:] = [k/layout.total_elements for k in j]
     b[i][0] = layout.is_sorted_stack(i)
  b.shape=(S,(layout.H + 1))
  return b

#overriding the function in the module
cpmp_ml.get_ann_state = get_ann_state

In [9]:
#************ | convert_label() | ************#
# El proposito de esta función es convertir   #  
# una matriz en una lista con los datos       #
# apilados de forma que una red neuronal los  #
# use como etiquetas.                         #
#                                             #
# Input:                                      #
#     - score: Una matriz con datos binarios. #
#                                             #
# Output:                                     #
#      Retorna una lista con los datos de la  #
#      matriz apilados.                       #      
def convert_label(score: np.ndarray) -> np.ndarray:
    list_score = []

    for i in score:
        list_score.append(i)

    return np.array(list_score)

In [10]:
#************ | generate_steps_of_a_state() | *****************#
# El proposito de esta función es generar todos los            #
# movimientos que resuelven un estado a través de un algorimo  #
# greedy.                                                      #
#                                                              #
# Input:                                                       #
#     - layout: El estado actual que se desea resolver.        #
#                                                              #
# Output:                                                      #
#      - states: Lista de todos los estados de la solución.    #
#      - source_tags: Lista de todos los stacks de origen.     #
#      - destination_tags: Lista de todos los stacks de        #
#                          destino.                            #
#       En caso de no poder resolver el estado actual,         #
#       cada una de las variables antes mencionadas retorna    #
#       None.                                                  #
def generate_steps_of_a_state(layout: cpmp_ml.Layout) -> tuple:
    states = [] # estados antes de movimiento
    source_tags = [] # etiquetas origen
    destination_tags = []  # etiquetas destino

    aux = deepcopy(layout)  # creación de copia de objeto

    steps, moves = greedy(aux)
    if steps == -1:
      return None, None, None

    for i in range(steps):
        states.append(get_ann_state(layout)) # antes del movimiento
        source_tags.append(convert_label(to_categorical(moves[i][0],len(layout.stacks))))
        destination_tags.append(convert_label(to_categorical(moves[i][1],len(layout.stacks))))
        layout.move(moves[i])
        aux = deepcopy(layout)

    return states, source_tags, destination_tags

In [11]:
#*************** | create_different_states() | ***************#
# El proposito de esta función es crear diferentes            #
# estados para el problema CPMP con sus respectivas           #
# soluciones calculadas con un algoritmo greedy.              #
#                                                             #
# Input:                                                      #
#     - S: Cantidad de stacks.                                #
#     - H: Altura de los stacks                               #
#     - max_priority_container: la prioridad máxima de        #
#                               los contenedores y a la       #
#                               vez el total de contenedores. #
#     - n: cantidad de nuevos estados.                        #
# Output:                                                     #
#     Retorna arreglos que representan los distintos          #
#     estados con otros dos arreglos que contienen sus        #
#     posibles stacks de origen y de destino.                 #
def create_different_states(S: int, H: int, 
                            max_priority_container: int, n: int
                            ) -> tuple:
  data_state = []
  labels_source = []
  labels_destination = []
  iter = 0
  while iter < n:
    layout = generate_random_layout(S,H,max_priority_container)
    state, source, destination = generate_steps_of_a_state(layout)
    if state == None and source == None and destination == None: continue
    unlist(data_state,labels_source,labels_destination,state,source,destination)
    iter+=1

  return np.stack(data_state), np.stack(labels_source), np.stack(labels_destination)

In [12]:
#*************** | concatenate_state_with_output() | ****************#
# El proposito de esta función es concatenar la data de las estados  #
# del problema con sus respectivos labels que indican el stack de    #
# origen.                                                            #
#                                                                    #
# Input:                                                             #
#     - states: Lista de matrices indicando los diversos estados.    #
#     - outputs: Lista de stacks de origen.                          #
#                                                                    #
# Output:                                                            # 
#      Retorna un arreglo con los datos concatenados.                #
def concatenate_states_with_outputs(states: list, outputs: list) -> np.ndarray:
    size_stacks = len(states[0])
    size_height = len(states[0][0])
    tuple_data = zip(states, outputs)
    new_data = []

    for state, output in tuple_data:
        new_data.append([])

        for i in range(size_stacks):
            stack = state[i].tolist()
            stack.append(output[i])
            new_data[len(new_data) - 1].append(stack)

    return np.stack(new_data)

In [13]:
#*************** | concatenate_state_with_output() | ******************#
# El proposito de esta función es concatenar un estado con los         #
# posibles stacks de origen.                                           #
#                                                                      #
# Input:                                                               #
#     - state: Arreglo que contiene un estado del problema.            #
#     - output: Arreglo que contiene los posibles stacks de origen.    #
#     - S: Cantidad de stacks.                                         #
# Output:                                                              #
#     Retorna el estado concatenado.                                   #
def concatenate_state_with_output(state: np.ndarray, 
                                  output: np.ndarray, S: int
                                  ) -> np.ndarray:
    state_aux = deepcopy(state)
    new_state = []
    for i in range(S):
        stack = state_aux[i].tolist()
        stack.append(output[i])
        new_state.append(stack)

    return np.stack(new_state)

In [14]:
#************* | get_so_sd_train() | **************#
# El proposito de esta función es obtener los      #
# stacks de origen y destino de un estado n x m.   #
#                                                  #
# Input:                                           #
#     - data: Lista de estados                     #
#     - labels: Lista de stacks descritos en un    #
#               arreglo de largo n * m.            #
#     - S: Cantidad de stacks                      #
#     - H: Altura de los estados                   #
#     - verbose: variable para activar el          #
#                seguimiento de la función.        #
def get_so_sd_train(data: list, labels: list, 
                    S: int = 5, H: int = 5, 
                    verbose: bool = False) -> tuple:
  so_train = []
  sd_train = []
  i = 0
  data_2 = []
  size = len(labels)

  for i in range(size):
    so = np.zeros(S)
    k=0
    size_2 = len(labels[i])
    flag = False
    for j in range(size_2):
      if labels[i][j] == 1.0:
        move = get_move(k,S,H)

        if not flag:
          aux = move[0]
          sd = np.zeros(S)
          so_aux = np.zeros(S)
          so_aux[aux] = 1.
          data_2.append(concatenate_state_with_output(data[i], so_aux, S))
          sd[move[1]] = 1.
          flag = True
        elif aux != move[0]:
          aux = move[0]
          sd_train.append(sd)
          so_aux = np.zeros(S)
          sd = np.zeros(S)
          so_aux[aux] = 1.
          data_2.append(concatenate_state_with_output(data[i], so_aux, S))
          sd[move[1]] = 1.
        else:
          sd[move[1]] = 1.

        if verbose: print("optimal_move:", move)

        so[move[0]]= 1.0

      k+=1
    if verbose: print("")
    sd_train.append(sd)
    so_train.append(so)
    i += 1

  
  return np.array(data_2), np.array(so_train), np.array(sd_train)

## Funciones para guardar y generar datos

In [15]:
#***************** | save_data() | *****************#
# El proposito de esta función es almacenar datos   #
# de entrenamiento en un archivo csv.               #
#                                                   #
# Input:                                            #
#     - data: Lista de matrices con los estados     #
#             correspondientes.                     #
#     - labels_1: Lista con los posibles stacks de  #   
#                 origen.                           #
#     - labels_2: Lista con los posibles stacks de  #
#                 destino.                          #
#     - name: Dirección y/o nombre del archivo      #
#             sin el .csv.                          #
# Output:                                           #
#      No retorna valores.                          #
def save_data(data: list, labels_1: list, labels_2: list, name: str) -> None:
    size_stack = len(data[0])
    size_height = len(data[0][0])
    total_data = len(data)
    tuple_data = zip(data, labels_1, labels_2)

    with open(name + '.csv', 'w') as archivo:
        archivo.write('Total data: ' + str(total_data) + '\n')
        archivo.write('Stacks:' + str(size_stack) + ',Height:' + str(size_height) + '\n')
        archivo.write('\n')

        for matrix, label_1, label_2 in tuple_data:
            lista_stack = matrix.flatten()
            archivo.write('matrix:' + str(lista_stack.tolist())[1:-1] + '\n')
            archivo.write('label_1:' + str(label_1.tolist())[1:-1] + '\n')
            archivo.write('label_2:' + str(label_2.tolist())[1:-1] + '\n')
            archivo.write('\n')

        archivo.close()

In [16]:
def load_data_2(name: str) -> tuple:
    data = []
    labels = []

    with open(name + '.csv', 'r') as archivo:
        total = int(archivo.readline().split(':')[1])
        line = archivo.readline().split(':')
        size_stacks = int(line[1].split(',')[0])
        size_height = int(line[2])
        archivo.readline()

        for i in range(total):
            matrix = archivo.readline().split(':')[1].split(',')
            matrix = np.array(matrix, dtype= float)
            matrix = np.reshape(matrix, (size_stacks, size_height))

            label_1 = archivo.readline().split(':')[1].split(',')
            label_1 = np.array(label_1, dtype= float)

            data.append(matrix)
            labels.append(label_1)

            archivo.readline()

    return np.stack(data), np.stack(labels)

In [17]:
#************** | load_data() | ************#
# El proposito de esta función es cargar    #
# los datos almacenados en un csv para el   #
# entrenamiento de la red neuronal.         #
#                                           #
# Input:                                    #
#     - name: Nombre del archivo con su     #
#             dirección correspondiente     #
#             sin el .csv.                  #
#                                           #
# Output:                                   #
#      Retorna 3 arreglos, el primero       #
#      corresponde a una lista de estados,  #
#      el segundo a una lista de labels     #
#      de stacks de origen y por último una #
#      lista de posibles stacks de destino. #
def load_data(name: str) -> tuple:
    data = []
    labels_1 = []
    labels_2 = []

    with open(name + '.csv', 'r') as archivo:
        total = int(archivo.readline().split(':')[1])
        line = archivo.readline().split(':')
        size_stacks = int(line[1].split(',')[0])
        size_height = int(line[2])
        archivo.readline()

        for i in range(total):
            matrix = archivo.readline().split(':')[1].split(',')
            matrix = np.array(matrix, dtype= float)
            matrix = np.reshape(matrix, (size_stacks, size_height))

            label_1 = archivo.readline().split(':')[1].split(',')
            label_1 = np.array(label_1, dtype= float)
            label_2 = archivo.readline().split(':')[1].split(',')
            label_2 = np.array(label_2, dtype= float)

            data.append(matrix)
            labels_1.append(label_1)
            labels_2.append(label_2)

            archivo.readline()

    return np.stack(data), np.stack(labels_1), np.stack(labels_2)

In [18]:
#********************* | save_data_multi | *********************#
# El proposito de esta función es guardar la data creada        #
# en un archivo csv para que pueda ser usada más adelante.      #
#                                                               #
# Input:                                                        #
#     - data: Lista que contiene los estados sin repetición.    #
#     - data_2: Lista que contiene los estados con posible      #
#               repetición concatenados a sus stacks de origen. #
#     - labels_1: Posibles stacks de origen                     #
#     - labels_2: Posibles stacks de destino                    #
#     - name: Nombre del archivo                                #
# Output:                                                       #
#     Esta función no retorna valores.                          #
def save_data_multi(data: list, data_2: list, labels_1: list, labels_2: list, name: str) -> None:
    size_stack = len(data[0])
    size_height = len(data[0][0])
    total_data_1 = len(data)
    total_data_2 = len(data_2)
    tuple_data_1 = zip(data, labels_1)
    tuple_data_2 = zip(data_2, labels_2)

    with open(name + '_so.csv', 'w') as archivo:
        archivo.write('Total data: ' + str(total_data_1) + '\n')
        archivo.write('Stacks:' + str(size_stack) + ',Height:' + str(size_height) + '\n')
        archivo.write('\n')

        for matrix, label_1 in tuple_data_1:
            lista_stack = matrix.flatten()
            archivo.write('matrix_1:' + str(lista_stack.tolist())[1:-1] + '\n')
            archivo.write('label_1:' + str(label_1.tolist())[1:-1] + '\n')
            archivo.write('\n')

        archivo.close()

    with open(name + '_sd.csv', 'w') as archivo:
        archivo.write('Total data: ' + str(total_data_2) + '\n')
        archivo.write('Stacks:' + str(size_stack) + ',Height:' + str(size_height + 1) + '\n')
        archivo.write('\n')

        for matrix, label_2 in tuple_data_2:
            lista_stack = matrix.flatten()
            archivo.write('matrix_2:' + str(lista_stack.tolist())[1:-1] + '\n')
            archivo.write('label_2:' + str(label_2.tolist())[1:-1] + '\n')
            archivo.write('\n')

        archivo.close()

In [19]:
#**************** | load_data_multi() | *****************#
# El proposito de esta función es cargar la data         #
# guardad localmente de un archivo csv.                  #
#                                                        #
# Input:                                                 #
#     - name: Nombre del archivo                         #
# Output:                                                #
#     Esta función no retorna valores.                   # 
def load_data_multi(name: str) -> tuple:
    data = []
    data_2 = []
    labels_1 = []
    labels_2 = []

    with open(name + '_so.csv', 'r') as archivo:
        total = int(archivo.readline().split(':')[1])
        line = archivo.readline().split(':')
        size_stacks = int(line[1].split(',')[0])
        size_height = int(line[2])
        archivo.readline()

        for i in range(total):
            matrix = archivo.readline().split(':')[1].split(',')
            matrix = np.array(matrix, dtype= float)
            matrix = np.reshape(matrix, (size_stacks, size_height))

            label_1 = archivo.readline().split(':')[1].split(',')
            label_1 = np.array(label_1, dtype= float)

            data.append(matrix)
            labels_1.append(label_1)

            archivo.readline()
    
    with open(name + '_sd.csv', 'r') as archivo:
        total = int(archivo.readline().split(':')[1])
        line = archivo.readline().split(':')
        size_stacks = int(line[1].split(',')[0])
        size_height = int(line[2])
        archivo.readline()

        for i in range(total):
            matrix = archivo.readline().split(':')[1].split(',')
            matrix = np.array(matrix, dtype= float)
            matrix = np.reshape(matrix, (size_stacks, size_height))

            label_2 = archivo.readline().split(':')[1].split(',')
            label_2 = np.array(label_2, dtype= float)

            data_2.append(matrix)
            labels_2.append(label_2)

            archivo.readline()

    return np.stack(data), np.stack(data_2), np.stack(labels_1), np.stack(labels_2)

## Generador de data para un solo stack de origen y destino

In [28]:
# Cantidad de stacks
S = 5#@param {type:'slider',min:1,max:1000,steps:1}

# Altura de la bahía
H = 7#@param {type:'slider',min:1,max:1000,steps:1}

# Número máximo de prioridad
MPC = 32 #@param {type:'slider',min:1,max:1000,steps:1}

# Cantida casos de entrenamiento
N = 10000 #@param {type:'slider',min:1,max:100000,steps:1}

X_train, y_train_so, y_train_sd = create_different_states(S, H, MPC, N)

In [ ]:
# Cantidad de stacks
S2 = 3 #@param {type:'slider',min:1,max:100,steps:1}

# Altura de la bahía
H2 = 7 #@param {type:'slider',min:1,max:100,steps:1}

# Número máximo de prioridad
MPC2 = 12 #@param {type:'slider',min:1,max:100,steps:1}

# Cantida casos de prueba
N2 = 500 #@param {type:'slider',min:1,max:10000,steps:1}

X_test, y_test_so, y_test_sd = create_different_states(S2, H2, MPC2, N2)

## Generador de data para multiples stacks de origen y destino

In [ ]:
# Cantidad de stacks
S = 10#@param {type:'slider',min:1,max:1000,steps:1}

# Altura de la bahía
H = 10#@param {type:'slider',min:1,max:1000,steps:1}

# Número máximo de prioridad
MPC = 62 #@param {type:'slider',min:1,max:1000,steps:1}

# Cantida casos de entrenamiento
N = 100000 #@param {type:'slider',min:1,max:100000,steps:1}

data_so, labels = generate_data(S= S, H= H, N= MPC, sample_size= N, perms_by_layout= 1)
data_sd, labels_so, labels_sd = get_so_sd_train(data_so, labels, S= S, H= H) 


## Generador de data con modelo
### Función que es necesaria cambiar

In [20]:
def get_move_2(act, S=5,H=5):
  k=0
  for i in range(S):
    for j in range(H):
      if k==act: return (i,j)
      k+=1

cpmp_ml.get_move = get_move_2

### Cargar modelos

In [21]:
model_5x5 = cpmp_att.CPMP_attention_model()
model_5x5.set_model('models/model_cpmp_5x5.h5')

Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [ ]:
model_7x7 = cpmp_att.CPMP_attention_model()
model_7x7.set_model('models/model_cpmp_7x7.h5')

In [31]:
# Cantidad de stacks
S = 5#@param {type:'slider',min:1,max:1000,steps:1}

# Altura de la bahía
H = 5#@param {type:'slider',min:1,max:1000,steps:1}

# Número máximo de prioridad
MPC = 15 #@param {type:'slider',min:1,max:1000,steps:1}

# Cantida casos de entrenamiento
N = 15 #@param {type:'slider',min:1,max:100000,steps:1}

data_so, labels = generate_data2(model= model_5x5, S= S, H= H, N= MPC, sample_size= N, batch_size=20, perms_by_layout= 1)

In [32]:
data_so

[array([[1.        , 2.        , 2.        , 2.        , 0.86666667,
         0.4       ],
        [0.        , 2.        , 2.        , 0.2       , 0.26666667,
         0.33333333],
        [0.        , 2.        , 0.26666667, 0.46666667, 0.66666667,
         0.8       ],
        [1.        , 2.        , 2.        , 0.93333333, 0.66666667,
         0.53333333],
        [0.        , 2.        , 2.        , 0.4       , 0.33333333,
         0.4       ]]),
 array([[1.        , 2.        , 2.        , 2.        , 0.73333333,
         0.53333333],
        [0.        , 0.13333333, 0.2       , 0.46666667, 0.2       ,
         0.26666667],
        [1.        , 2.        , 2.        , 2.        , 2.        ,
         2.        ],
        [0.        , 2.        , 2.        , 0.66666667, 0.2       ,
         0.33333333],
        [0.        , 1.        , 0.86666667, 0.53333333, 0.4       ,
         0.73333333]]),
 array([[0.        , 2.        , 0.8       , 0.33333333, 0.46666667,
         0.933333

In [33]:
labels

[array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 