In [1]:
import keras
import numpy as np

In [8]:
class OutputMultiplication(keras.layers.Layer):
    def __init__(self):
        super(OutputMultiplication,self).__init__(trainable=False)

    def call(self, arr1, arr2):
        return arr1 * arr2
    
# Ejemplo:
OutputMultiplication()(np.array([1.,0.,1.]), np.array([0.3783, 1.49331, 9.128]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.3783, 0.    , 9.128 ], dtype=float32)>

In [3]:
class LayerExpandOutput(keras.layers.Layer):
    def __init__(self):
        super(LayerExpandOutput, self).__init__(trainable=False)

    def call(self, arr):
        list_arr = []
        for val in arr:
            list_arr.append(np.full((1,arr.shape[0]),val))
        return np.hstack(list_arr)[0]
    
# Ejemplo:
#   Entrada: [1,0,1]
#   Salida: [1,1,1,0,0,0,1,1,1]
LayerExpandOutput()(np.array([1,0,1]))

array([1, 1, 1, 0, 0, 0, 1, 1, 1])

In [2]:
class ConcatenateLayerState(keras.layers.Layer):
    def __init__(self):
        super(ConcatenateLayerState,self).__init__()

    def call(self, state, label):

        matrix = []
        for i in range(state.shape[0]):
            matrix.append(np.concatenate((state[i],[label[i]])))


        return np.array(matrix)
    
# Ejemplo:
ConcatenateLayerState()(np.random.rand(5, 5), np.array([1,0,0,1,0]))

array([[0.82338518, 0.69404495, 0.48350379, 0.81435478, 0.23986442,
        1.        ],
       [0.85840529, 0.8814683 , 0.21083336, 0.36816698, 0.72597241,
        0.        ],
       [0.50789469, 0.68273425, 0.63497764, 0.29485685, 0.36489388,
        0.        ],
       [0.27518976, 0.42578569, 0.55538601, 0.04953451, 0.45260999,
        1.        ],
       [0.49883601, 0.03995382, 0.46985194, 0.08436211, 0.0850969 ,
        0.        ]])

In [ ]:
def create_model_CPMP_Nacho(source_model, destination_model, S, H):
    input = keras.layers.Input(shape= (S,H+1))
    output_source_model = LayerExpandOutput()(source_model(input))
    
    return model

In [ ]:
def create_model_CPMP_LosWillyAmigos(source_model, destination_model, S, H):
    input = keras.layers.Input(shape= (S,H+1))
    concat = ConcatenateLayerState()(input,source_model(input))
    output = destination_model(concat)
    model = keras.Model(inputs=input,outputs=output)

    for layer in model.layers:
        layer.trainable=False

    return model